services:
  hpc:
    image: hh-nvhpc:latest
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    user: "${UID}:${GID}"
    volumes:
      - "${HOME}:${HOME}"
      - "/scr:/scr"
    working_dir: "${HOME}"
    stdin_open: true
    tty: true
    network_mode: host