services:
  hpc:
    image: hh-nvhpc:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    user: "${UID}:${GID}"
    volumes:
      - "${HOME}:${HOME}"
      - "/scr:/scr"
    working_dir: "${HOME}"
    stdin_open: true      # = -i
    tty: true             # = -t
    restart: "no"         # 同じく --rm の意味合い